import {
  Anchor,
  Bed,
  Berth,
  Bnb,
  Boat,
  Breadth,
  Cabin,
  Calendar,
  Cancel,
  Cash,
  Check,
  Checkbox,
  Chevron,
  Company,
  Door,
  Eth,
  Eur,
  Feet,
  Filter,
  Gift,
  Length,
  Location,
  Mainsail,
  Osean,
  Search,
  Settings,
  Shower,
  Usd,
  WC,
} from "./svgs/svgs";

export const ICON_TYPE: {
  [key: string]: {
    [key: string]: React.ComponentType<any>; // Adjust the type according to your component types
  };
} = {
  SVGS: {
    anchor: Anchor,
    bed: Bed,
    calendar: Calendar,
    feet: Feet,
    gift: Gift,
    location: Location,
    shower: Shower,
    door: Door,
    company: Company,
    checkbox: Checkbox,
    cash: Cash,
    boat: Boat,
    berth: Berth,
    settings: Settings,
    chevron: Chevron,
    cabin: Cabin,
    wc: WC,
    breadth: Breadth,
    mainsail: Mainsail,
    length: Length,
    check: Check,
    search: Search,
    filter: Filter,
    cancel: Cancel,
    usd: Usd,
    eth: Eth,
    bnb: Bnb,
    osean: Osean,
    eur: Eur,
  },
};
